---
kind: pipeline
type: docker
name: CI

steps:
  # TESTING #
  - name: test
    image: node:lts-alpine
    commands:
      - yarn --immutable --immutable-cache --check-cache
      - yarn run prettier:check

  # FEATURE BUILD (LOCAL) #
  - name: build
    when:
      branch:
        exclude:
          - main
          - dev
    image: node:lts-alpine
    commands:
      - yarn build

  # DEV BUILD #
  - name: build & deploy to dockerhub (dev)
    image: crazymax/docker:latest
    when:
      branch: dev
    environment:
      DOCKER_ACCESS_KEY:
        from_secret: DOCKER_ACCESS_KEY
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo $DOCKER_ACCESS_KEY | docker login -u mauricenino --password-stdin
      - docker buildx create --name builder --driver docker-container --use
      - docker buildx inspect --bootstrap --builder builder
      - docker buildx build --platform linux/amd64 -t mauricenino/dashdot:dev -o type=registry .
      - docker logout
  - name: update & deploy server files (dev)
    image: docker/compose
    when:
      branch: dev
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - docker image pull mauricenino/dashdot:dev
      - cd /server && ./start.sh dashdot

  # PROD BUILD #
  - name: build & deploy to dockerhub (production)
    image: crazymax/docker:latest
    when:
      branch: main
    environment:
      DOCKER_ACCESS_KEY:
        from_secret: DOCKER_ACCESS_KEY
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - |
        sed 's/.*"version": "\(.*\)".*/\1/;t;d' ./package.json > package.version
      - echo $DOCKER_ACCESS_KEY | docker login -u mauricenino --password-stdin
      - docker buildx create --name builder --driver docker-container --use
      - docker buildx inspect --bootstrap --builder builder
      - docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64/v8 -t mauricenino/dashdot:latest -t mauricenino/dashdot:$(cat package.version) -o type=registry .
      - docker logout
  - name: update & deploy server files
    image: docker/compose
    when:
      branch: main
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - docker image pull mauricenino/dashdot:latest
      - cd /server && ./start.sh dashdot

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: server
    host:
      path: /server

---
kind: secret
name: DOCKER_ACCESS_KEY
data: ysbzIhceuQjxnBZ7kRt63CswtG85WTCiCBFPCM8wmV9qBQTS9kGPktIqw1wevm1O0U2l1pTWl7wt2e7D+a462Q==
---
kind: signature
hmac: de28f0f0b84d41af121f1b8ff2a2a2853c08fb91cf99fe6df2301984b3d92d35
