---
kind: pipeline
type: docker
name: CI

steps:
  # DEPENDENCIES #
  - name: dependencies
    image: timbru31/node-alpine-git:latest
    when:
      event:
        - push
    commands:
      - yarn --immutable --immutable-cache
  - name: dependencies (pr)
    image: timbru31/node-alpine-git:latest
    when:
      event:
        - pull_request
    commands:
      - yarn --immutable --immutable-cache --check-cache

  # TESTING #
  - name: test
    image: timbru31/node-alpine-git:latest
    when:
      event:
        - push
        - pull_request
    commands:
      - yarn test

  # FEATURE BUILD (LOCAL) #
  - name: build
    when:
      event:
        - push
        - pull_request
      branch:
        exclude:
          - main
          - dev
    image: timbru31/node-alpine-git:latest
    commands:
      - yarn build

  # DEV BUILD #
  - name: build & release (dockerhub) (dev)
    image: crazymax/docker:latest
    when:
      event: push
      branch: dev
    environment:
      DOCKER_ACCESS_KEY:
        from_secret: DOCKER_ACCESS_KEY
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo $DOCKER_ACCESS_KEY | docker login -u mauricenino --password-stdin
      - docker buildx create --name builder --driver docker-container --use
      - docker buildx inspect --bootstrap --builder builder
      - docker buildx build
        --platform linux/amd64
        --target prod
        --label org.opencontainers.image.title="dash."
        --label org.opencontainers.image.description="dash. - a modern server dashboard"
        --label org.opencontainers.image.authors="MauriceNino <mauriceprivat98@gmail.com>"
        --label org.opencontainers.image.url=https://github.com/MauriceNino/dashdot
        --label org.opencontainers.image.source=https://github.com/MauriceNino/dashdot
        --label org.opencontainers.image.licenses=MIT
        -o type=registry
        -t mauricenino/dashdot:dev .
  - name: update & deploy server files (dev)
    image: docker/compose
    when:
      event: push
      branch: dev
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - docker image pull mauricenino/dashdot:dev
      - cd /server && ./start.sh dashdot

  # PROD BUILD #
  - name: build (production)
    image: crazymax/docker:latest
    when:
      event: push
      branch: main
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker buildx create --name builder --driver docker-container --use
      - docker buildx inspect --bootstrap --builder builder
      - docker buildx build
        --platform linux/amd64,linux/arm/v7,linux/arm64/v8
        --target prod
        --label org.opencontainers.image.title="dash."
        --label org.opencontainers.image.description="dash. - a modern server dashboard"
        --label org.opencontainers.image.authors="MauriceNino <mauriceprivat98@gmail.com>"
        --label org.opencontainers.image.url=https://github.com/MauriceNino/dashdot
        --label org.opencontainers.image.source=https://github.com/MauriceNino/dashdot
        --label org.opencontainers.image.licenses=MIT
        -t mauricenino/dashdot .
  - name: release (dockerhub & github)
    image: crazymax/docker:latest
    when:
      event: push
      branch: main
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      DOCKER_USERNAME: mauricenino
      DOCKER_PASSWORD:
        from_secret: DOCKER_ACCESS_KEY
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - apk add git nodejs yarn
      - yarn semantic-release
  - name: update & deploy server files
    image: docker/compose
    when:
      event: push
      branch: main
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - docker image pull mauricenino/dashdot:latest
      - cd /server && ./start.sh dashdot

  # CLEANUP #
  - name: cleanup
    image: crazymax/docker:latest
    when:
      status:
        - failure
        - success
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker logout

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: server
    host:
      path: /server

---
kind: secret
name: DOCKER_ACCESS_KEY
data: aRlMTaj5z6fMgCnFDDiLTPakLlcziQvZxw0K8k06ZsIdeGshKPMzMhl4+UoiC4rCaDtsnu0hmcXeIzqP83NQXw==
---
kind: secret
name: GITHUB_TOKEN
data: JMpZE0aC5Fau1tDEh+6Huy+yZJF1BqhVAzIm7+Xvfx9vYxHRrPAbh6hZrJzEvEjK9ClGNoPCHJaKmezV3Yrt2qYsARU=
---
kind: signature
hmac: c16f3c872a9b22e71a16ba097f1354065e541d64ed91008684d50733a278a866
