---
kind: pipeline
type: docker
name: CI

steps:
  # DEPENDENCIES #
  - name: dependencies
    image: timbru31/node-alpine-git:latest
    when:
      event:
        - push
    commands:
      - yarn --immutable --immutable-cache
  - name: dependencies (pr)
    image: timbru31/node-alpine-git:latest
    when:
      event:
        - pull_request
    commands:
      - yarn --immutable --immutable-cache --check-cache

  # TESTING #
  - name: test
    image: timbru31/node-alpine-git:latest
    when:
      event:
        - push
        - pull_request
    commands:
      - yarn test

  # FEATURE BUILD (LOCAL) #
  - name: build
    when:
      event:
        - push
        - pull_request
      branch:
        exclude:
          - main
          - dev
    image: timbru31/node-alpine-git:latest
    commands:
      - yarn build

  # DEV BUILD #
  - name: build & deploy to dockerhub (dev)
    image: crazymax/docker:latest
    when:
      event: push
      branch: dev
    environment:
      DOCKER_ACCESS_KEY:
        from_secret: DOCKER_ACCESS_KEY
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo $DOCKER_ACCESS_KEY | docker login -u mauricenino --password-stdin
      - docker buildx create --name builder --driver docker-container --use
      - docker buildx inspect --bootstrap --builder builder
      - docker buildx build --platform linux/amd64 -t mauricenino/dashdot:dev -o type=registry .
      - docker logout
  - name: update & deploy server files (dev)
    image: docker/compose
    when:
      event: push
      branch: dev
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - docker image pull mauricenino/dashdot:dev
      - cd /server && ./start.sh dashdot

  # PROD BUILD #
  - name: build (production)
    image: crazymax/docker:latest
    when:
      event: push
      branch: main
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker buildx create --name builder --driver docker-container --use
      - docker buildx inspect --bootstrap --builder builder
      - docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64/v8 -t mauricenino/dashdot .
  - name: create release
    image: timbru31/node-alpine-git:latest
    when:
      event: push
      branch: main
    environment:
      DOCKER_USERNAME: mauricenino
      DOCKER_PASSWORD:
        from_secret: DOCKER_ACCESS_KEY
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - yarn semantic-release
  - name: update & deploy server files
    image: docker/compose
    when:
      event: push
      branch: main
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - docker image pull mauricenino/dashdot:latest
      - cd /server && ./start.sh dashdot

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: server
    host:
      path: /server

---
kind: secret
name: DOCKER_ACCESS_KEY
data: ysbzIhceuQjxnBZ7kRt63CswtG85WTCiCBFPCM8wmV9qBQTS9kGPktIqw1wevm1O0U2l1pTWl7wt2e7D+a462Q==
---
kind: secret
name: GITHUB_TOKEN
data: JMpZE0aC5Fau1tDEh+6Huy+yZJF1BqhVAzIm7+Xvfx9vYxHRrPAbh6hZrJzEvEjK9ClGNoPCHJaKmezV3Yrt2qYsARU=
---
kind: signature
hmac: e55608559b03786bcb131513bcd94268618d041e87daa4ddb1900f0599cc036f

...
