---
kind: pipeline
type: docker
name: CI

steps:
  - name: test
    image: node:lts-alpine
    commands:
      - yarn --ignore-scripts --frozen-lockfile
      - yarn run prettier:check
  - name: build
    image: docker:dind
    when:
      branch:
        exclude:
          - master
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker image build -t mauricenino/dashdot .
  - name: build & deploy to dockerhub
    image: crazymax/docker:latest
    when:
      branch: master
    environment:
      DOCKER_ACCESS_KEY:
        from_secret: DOCKER_ACCESS_KEY
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - |
        sed 's/.*"version": "\(.*\)".*/\1/;t;d' ./package.json > package.version
      - echo $DOCKER_ACCESS_KEY | docker login -u mauricenino --password-stdin
      - docker buildx create --name builder --driver docker-container --buildkitd-flags '--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host' --use
      - docker buildx inspect --bootstrap --builder builder
      - docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64/v8 -t mauricenino/dashdot:latest -t mauricenino/dashdot:$(cat package.version) -o type=registry .
      - docker logout
  - name: update & deploy server files
    image: docker/compose
    when:
      branch: master
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - cd /server/_repos/dashdot
      - apk add git
      - git config --global --add safe.directory /server/_repos/dashdot
      - git pull --rebase
      - cd /server
      - ./start.sh dashdot --build

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: server
    host:
      path: /server

---
kind: secret
name: DOCKER_ACCESS_KEY
data: ysbzIhceuQjxnBZ7kRt63CswtG85WTCiCBFPCM8wmV9qBQTS9kGPktIqw1wevm1O0U2l1pTWl7wt2e7D+a462Q==
---
kind: signature
hmac: d5223b7c83523091360162a99c42dd1be14cb94a4747cbf92a331c537913a01f
