# !! Attention !!
# This is a docker-compose file used ONLY for the dev environment and can not be used for production.
# If you need instructions on how to run dashdot, please have a look at the README.md file in the root of the project.
version: '3.5'

services:
  dash:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    tty: true
    command: yarn run serve
    restart: unless-stopped
    privileged: true
    environment:
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_ENABLE_STORAGE_SPLIT_VIEW=true
    ports:
      - 3000:3000 # view
      - 3001:3001 # api
      - 3002:3002 # docs
    volumes:
      - ./:/app
      - /etc/os-release:/etc/os-release:ro
      - /proc/1/ns/net:/mnt/host_ns_net:ro
      - /media:/mnt/host_media:ro
      - /mnt:/mnt/host_mnt:ro
