# !! Attention !!
# This is a docker-compose file used ONLY for the dev environment and can not be used for production.
# If you need instructions on how to run dashdot, please have a look at the README.md file in the root of the project.
version: '3.5'

services:
  frontend:
    image: node:16-alpine
    command: yarn run dev
    working_dir: /app/frontend
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    stdin_open: true
    tty: true
    restart: unless-stopped
    privileged: true
    environment:
      - DASHDOT_DISABLE_TILT=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - /etc/os-release:/etc/os-release:ro
