# !! Attention !!
# This is a docker-compose file used ONLY for the dev environment and can not be used for production.
# If you need instructions on how to run dashdot, please have a look at the README.md file in the root of the project.
version: '3.5'

services:
  dash:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        TARGETPLATFORM: linux/amd64         # or linux/arm64
    working_dir: /app
    tty: true
    command: yarn run serve
    restart: unless-stopped
    privileged: true
    environment:
      - DASHDOT_ENABLE_CPU_TEMPS=true
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - ./:/app
      - /etc/os-release:/etc/os-release:ro
      - /proc/1/ns/net:/mnt/host_ns_net:ro
      - /media:/mnt/host_media:ro
      - /mnt:/mnt/host_mnt:ro
