# !! Attention !!
# This is a docker-compose file used ONLY for the dev environment and can not be used for production.
# If you need instructions on how to run dashdot, please have a look at the README.md file in the root of the project.
version: '3.5'

services:
  frontend:
    image: node:16-alpine
    working_dir: /app/frontend
    command: yarn run dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./:/app

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    working_dir: /app/backend
    command: yarn run dev
    restart: unless-stopped
    privileged: true
    environment:
      - DASHDOT_ENABLE_CPU_TEMPS=true
    network_mode: host
    volumes:
      - ./:/app
      - /etc/os-release:/etc/os-release:ro

  shared:
    image: node:16-alpine
    working_dir: /app/shared
    command: yarn run dev
    restart: unless-stopped
    volumes:
      - ./:/app
