version: '3.5'

services:
  frontend:
    image: node:16-alpine
    command: yarn run dev
    working_dir: /app/frontend
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - DASHDOT_OVERRIDE_DISTRO=Test Server
      - DASHDOT_OVERRIDE_RELEASE=0.0.0
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app/backend
      - ./common:/app/common
